version: "3"
services:
  assistant-hub:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
